<?php

require_once('ExcepcionPropiaClase.php');

try {
    ExcepcionPropiaClase::testNumber(5);
    echo "NÃºmero valido";
} catch (ExcepcionPropia $e) {
    echo "Erro".$e->getMessage();
}

try {
    ExcepcionPropiaClase::testNumber(0);
    echo "NÃºmero vÃ¡lido";
} catch (ExcepcionPropia $e) {
    echo "Erro".$e->getMessage();
}